server :
  port : 42308
  ssl:
    enabled: true
    key-store: "keystore.pkcs12"
    key-store-password: esipe
    keyStoreType: PKCS12

spring :
  data :
    mongodb :
      uri: mongodb+srv://ejmn-converter:Ejmn2019@clustermongodb-driver-xusit.azure.mongodb.net/ezipflix?retryWrites=true&w=majority
      database : ezipflix




