# Java Maven CircleCI 2.0 configuration file
#
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    steps:
      - checkout
      - run: mvn package -B"