spring :
  data :
    mongodb :
      host : 172.31.249.153
      port : 27017
      database : ezipflix
      collections :
        video-conversions : video_conversions
conversion:
  messaging :
    video-status:
      url: wss://172.31.249.178:42308/video_status
#      url: ws://darkops:42308/video_status
    rabbitmq :
      conversion-exchange: video-conversion-exchange
      conversion-queue: video-conversion-queue

rabbitmq-server:
  server: 172.31.249.234
  port: 5672
  credentials:
    vhost: ezip         # sudo rabbitmqctl add_vhost ezip           # sudo rabbitmqctl set_permissions -p ezip ezip ".*" ".*" ".*"
    username: rabbitmq  # sudo rabbitmqctl add_user ezip pize
    password: rabbitmq