server :
  port : 42308
  ssl:
    enabled: true
    key-store: "keystore.pkcs12"
    key-store-password: esipe
    keyStoreType: PKCS12

spring :
  data :
    mongodb :
      host : 172.31.249.153
      port : 27017
      database : ezipflix

conversion:
  messaging :
    rabbitmq :
      conversion-exchange: video-conversion-exchange
      conversion-queue: video-conversion-queue

rabbitmq-server:
  server: 172.31.249.234
  port: 5672
  credentials:
    vhost: ezip         # sudo rabbitmqctl add_vhost ezip
                        # sudo rabbitmqctl set_permissions -p ezip ezip ".*" ".*" ".*"
    username: rabbitmq      # sudo rabbitmqctl add_user ezip pize
    password: rabbitmq


